### PR TITLE
Sheet 01 Submission

### PR DESCRIPTION
**Pull request by johannwagner**

### CODE REVIEW

**Comment by johannwagner** [comment]
Fixed.

**Comment by mmmohsen** [comment]
Hi Johann,
4 the first exercise sheet, you need to make the pull to the branch "sheet_01_material" as stated at the exercise sheet.
submissions branch is 4 the second sheet.
 
All the best,
Mahmoud

**Comment by johannwagner** [comment]
Thanks a lot !

**Comment by mmmohsen** [comment]
you are welcome

**Pull request merged**
