### PR TITLE
sheet 06

### PR DESCRIPTION
**Pull request by ranjan-venkatesh**
Sheet 06 submission

### CODE REVIEW

**Comment by mmmohsen** [comment]
unfortunately, I can't accept the submission since it is 4 minutes after the deadline.
sorry again

**Comment by ranjan-venkatesh** [comment]
Hi Mohsen,

It would be really great, if it can be considered for submission. I am
extremely sorry for the delay.

The total points for the evaluation also can be reduced to make up the
delay. But kindly re-consider the submission.

Thank you,
Ranjan Venkatesh

**Comment by mmmohsen** [comment]
I'm sorry Ranjan about it, but I really can't.  you can to talk to Marcus about if you like.
anyway did you receive the mail regarding the projects, if not please send me an email.

**Comment by ranjan-venkatesh** [comment]
I am unable to find your email address, could you share me the same or let me know where is it available?

**Comment by pinnecke** [comment]
Hi Rajan,

of course you are able to. Have a look at the first slide set in the lecture, where the organization is explained. You can find all relevant mail addresses, including mine of course in the repository you know https://github.com/Arcade-Lecture/lecture

Best
Marcus

**Pull request closed without merging**
